name: Deploy Infrastructure (Self-Bootstrapping)

on:
  push:
    branches:
      - dev

jobs:
  DeployToAwsWithTerraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # Necessário para autenticação com a AWS via OIDC
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build Java project with Maven
        run: mvn clean package

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6 
          cli_config_credentials_token: ${{ secrets.TFE_API_TOKEN }}

      - name: 'Phase 1: Bootstrap TFC Workspace'
        id: bootstrap
        shell: bash
        working-directory: ./terraform/bootstrap
        env:
          # Token do TFC com permissão para criar workspaces
          TFE_TOKEN: ${{ secrets.TFE_API_TOKEN }}
          TF_API_TOKEN: ${{ secrets.TFE_API_TOKEN }}
          TF_TOKEN: ${{ secrets.TFE_API_TOKEN }}
        run: |

          WORKSPACE_NAME="${{ github.event.repository.name }}"
          echo "Workspace a ser criado/assegurado: $WORKSPACE_NAME"
          
          # Este init usa o backend local (padrão), pois não há bloco de backend aqui
          terraform init
          
          # O apply cria o recurso tfe_workspace no Terraform Cloud
          terraform apply -auto-approve -var="workspace_name=$WORKSPACE_NAME" -var="repo_identifier=${{ github.repository }}"

      - name: 'Phase 2: Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ 'us-west-2' }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsRole
          role-session-name: github-action-terraform-deploy

      - name: 'Phase 2: Deploy Application via TFC'
        id: deploy_app
        working-directory: ./terraform/app
        env:
          # Token para autenticar com o backend remoto do TFC
          TFE_TOKEN: ${{ secrets.TFE_API_TOKEN }}
          TF_WORKSPACE: ${{ github.event.repository.name }}
        run: |
          # Este init vai se conectar ao backend remoto no workspace criado na Fase 1
          terraform init
          
          # O estado será gerenciado pelo Terraform Cloud
          terraform apply -auto-approve